### ISSUE TITLE
SPI help

### ISSUE THREAD

**Issue by joshbrew** [icl-rocketry/ADS131M04-Lib#7]
Hey, appreciate you posting this. I modified the library for the 8 channel device here (free brd files too, very basic breakout board design): https://github.com/moothyknight/ADS131M08_Arduino
but I am stumped trying to get response from it, I just get a slow read out of 1111111111111100 in every register. I know I'm close.

This is on an ESP32. Do you know if I need pullups or anything?

**Comment by DanieleVBella** [comment]
Hey there, sorry for the very late response, this issue didn't give me a notification for some reason. I'm happy this library could be of use to you!

For your problem, in case it hasn't been solved yet, does everything else work apart from register reading, or does reading the channels also not work? In terms of our hardware, implementation, we used it for [another project within this organisation that is freely available](https://github.com/icl-rocketry/daq-hardware), so you can check that against yours. Ours also uses an ESP32.

**Comment by joshbrew** [comment]
@DanieleVBella  Hey no worries! It runs perfectly now! I am amazed at the signal quality on this thing, like .33uV with nothing but an LDO. We are able to use it for EEG at the high gain/higher impedance settings haha

**Comment by Dayanand1996** [comment]
`https://github.com/moothyknight/ADS131M08_Arduino` 
hey, you have not mentioned the pins used for connection with esp32 please help i for the same

**Comment by joshbrew** [comment]
look at the .ino file

**Comment by Dayanand1996** [comment]
sir as i can see there in no GPIOs set for connections
![image](https://user-images.githubusercontent.com/103891506/224620218-57b124fb-8b72-46ff-bd6f-3869a38e7080.png)

**Comment by Dayanand1996** [comment]
please share screen shot
